# Generated by Django 6.0.1 on 2026-03-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_entre_turnos', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100)),
                ('apellido', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('telefono', models.CharField(default=None, max_length=20)),
                ('edad', models.IntegerField(default=None)),
                ('obra_social', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ciudad', models.CharField(default=None, max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fecha_hora', models.DateTimeField(default=None)),
                ('encuentro', models.CharField(default=None, max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
    ]
