# Generated by Django 6.0.1 on 2026-02-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='paciente',
        ),
        migrations.AddField(
            model_name='turno',
            name='apellido',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='encuentro',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_hora',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
