# Generated by Django 6.0.1 on 2026-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
