# Generated by Django 6.0.1 on 2026-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_remove_turno_paciente_turno_apellido_turno_encuentro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
