# Generated by Django 6.0.1 on 2026-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_horario_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionturnos',
            name='tiempo_entre_turnos',
        ),
        migrations.AddField(
            model_name='configuracionturnos',
            name='minutos_entre_turnos',
            field=models.IntegerField(default=60),
        ),
    ]
