# Generated by Django 6.0.1 on 2026-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_remove_configuracionturnos_tiempo_entre_turnos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('habilitada', models.BooleanField(default=True)),
                ('con_consultorio', models.BooleanField(default=False)),
            ],
        ),
    ]
