# Generated by Django 6.0.1 on 2026-02-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionturnos',
            name='duracion_turno',
        ),
    ]
