# Generated by Django 6.0.1 on 2026-02-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_remove_configuracionturnos_duracion_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionturnos',
            name='tiempo_entre_turnos',
            field=models.TimeField(),
        ),
    ]
