# Generated by Django 6.0.1 on 2026-04-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='turnos.ciudad'),
        ),
    ]
