# Generated by Django 6.0.1 on 2026-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_configuracionturnos_tiempo_entre_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='edad',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='turno',
            name='obra_social',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='telefono',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
