# Generated by Django 6.0.1 on 2026-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_turno_edad_turno_obra_social_turno_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ciudad',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
