# Generated by Django 6.0.1 on 2026-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_remove_horario_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionturnos',
            name='email_notificaciones',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
