# Generated by Django 6.0.1 on 2026-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_turno_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='obra_social',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
