# Generated by Django 6.0.1 on 2026-03-07 05:48

from django.db import migrations
from datetime import time

def create_initial_horarios(apps, schema_editor):
    Horario = apps.get_model('turnos', 'Horario')

    dias = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
    ]

    for dia in dias:
        Horario.objects.create(
            dia_semana=dia,
            hora_apertura=time(12, 0),
            hora_cierre=time(18, 0),
        )


def delete_initial_horarios(apps, schema_editor):
    Horario = apps.get_model('turnos', 'Horario')

    dias = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
    ]

    Horario.objects.filter(dia_semana__in=dias).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_feriado'),
    ]

    operations = [
        migrations.RunPython(create_initial_horarios, delete_initial_horarios),
    ]
